/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import ConexionSql.ConexionDB;
import javax.swing.JOptionPane;

/**
 *
 * @author ricar
 */
public class frmTratamientoOrtodoncia extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmTratamientoOrtodoncia
     */
    public frmTratamientoOrtodoncia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel82 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        lbid = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        lbidplan = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        txtEJE = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtanguloA1 = new javax.swing.JTextField();
        jSeparator15 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtanguloG1 = new javax.swing.JTextField();
        jSeparator16 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtIMPA1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtJa1 = new javax.swing.JTextField();
        txtIS = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jSeparator17 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();
        txtII = new javax.swing.JTextField();
        jSeparator18 = new javax.swing.JSeparator();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtFHIS = new javax.swing.JTextField();
        jSeparator19 = new javax.swing.JSeparator();
        jSeparator20 = new javax.swing.JSeparator();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtANB82 = new javax.swing.JTextField();
        jSeparator21 = new javax.swing.JSeparator();
        jSeparator22 = new javax.swing.JSeparator();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jSeparator24 = new javax.swing.JSeparator();
        jSeparator25 = new javax.swing.JSeparator();
        txtPALS = new javax.swing.JTextField();
        txtANB80 = new javax.swing.JTextField();
        txtANB2 = new javax.swing.JTextField();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        txtPALI = new javax.swing.JTextField();
        jSeparator23 = new javax.swing.JSeparator();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        txtPTB = new javax.swing.JTextField();
        jSeparator26 = new javax.swing.JSeparator();
        jSeparator27 = new javax.swing.JSeparator();
        jSeparator28 = new javax.swing.JSeparator();
        lbnombre = new javax.swing.JLabel();
        lbapellido = new javax.swing.JLabel();
        lblnombre10 = new javax.swing.JLabel();
        chcurvaleve1 = new javax.swing.JCheckBox();
        chcurvamoderada1 = new javax.swing.JCheckBox();
        chcurvasevera = new javax.swing.JCheckBox();
        lblnombre6 = new javax.swing.JLabel();
        txtDSD = new javax.swing.JTextField();
        lblnombre9 = new javax.swing.JLabel();
        lblnombre8 = new javax.swing.JLabel();
        txtmaxilares = new javax.swing.JTextField();
        lblnombre7 = new javax.swing.JLabel();
        txtEntornoD = new javax.swing.JTextField();
        lblnombre11 = new javax.swing.JLabel();
        txtbandas = new javax.swing.JTextField();
        lblnombre12 = new javax.swing.JLabel();
        txttubos = new javax.swing.JTextField();
        lblnombre13 = new javax.swing.JLabel();
        txtotros = new javax.swing.JTextField();
        lblnombre14 = new javax.swing.JLabel();
        txtAparato = new javax.swing.JTextField();
        lblnombre15 = new javax.swing.JLabel();
        txtexodoncia = new javax.swing.JTextField();
        lblnombre17 = new javax.swing.JLabel();
        txtBrakets = new javax.swing.JTextField();
        lblnombre19 = new javax.swing.JLabel();
        txtRetenciones = new javax.swing.JTextField();
        lblnombre18 = new javax.swing.JLabel();
        txtsecuencia = new javax.swing.JTextField();
        lblnombre20 = new javax.swing.JLabel();
        txtMD = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jSeparator29 = new javax.swing.JSeparator();
        jSeparator30 = new javax.swing.JSeparator();
        jLabel87 = new javax.swing.JLabel();
        jSeparator31 = new javax.swing.JSeparator();
        jSeparator32 = new javax.swing.JSeparator();
        jSeparator33 = new javax.swing.JSeparator();
        jSeparator67 = new javax.swing.JSeparator();
        chmodelo = new javax.swing.JCheckBox();
        chfaciales = new javax.swing.JCheckBox();
        chpanoramica = new javax.swing.JCheckBox();
        chintraorales = new javax.swing.JCheckBox();
        jSeparator68 = new javax.swing.JSeparator();
        chmodeloMD = new javax.swing.JCheckBox();
        chcefalometrica = new javax.swing.JCheckBox();
        chincicivos = new javax.swing.JCheckBox();
        jSeparator69 = new javax.swing.JSeparator();
        jSeparator70 = new javax.swing.JSeparator();
        txtrocabado = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        btnBuscarEditar1 = new javax.swing.JButton();
        btnEditar1 = new javax.swing.JButton();
        btnGuardar1 = new javax.swing.JButton();
        btnCancelar1 = new javax.swing.JButton();
        btnBuscarEditar2 = new javax.swing.JButton();
        btnEditar2 = new javax.swing.JButton();
        btnGuardarPT2 = new javax.swing.JButton();
        btnCancelar2 = new javax.swing.JButton();
        btnElegirTP = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel82.setBackground(new java.awt.Color(255, 255, 255));
        jLabel82.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel82.setText("Expediente Ortodoncia");
        getContentPane().add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 280, 30));

        jLabel2.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jLabel2.setText("Para poder continuar debe elegir un paciente:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 200, 10, 110));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 1140, -1));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 1140, 10));

        jSeparator11.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator11.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 1140, 10));
        getContentPane().add(lbid, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 80, 57, 18));

        jSeparator12.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator12.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator12.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 200, -1, 110));

        lbidplan.setFont(new java.awt.Font("Baskerville Old Face", 1, 11)); // NOI18N
        getContentPane().add(lbidplan, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 70, 57, 18));

        jLabel3.setFont(new java.awt.Font("Baskerville Old Face", 0, 11)); // NOI18N
        jLabel3.setText("IS-LS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 210, 40, -1));

        jSeparator13.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator13.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 1140, 20));

        jLabel4.setFont(new java.awt.Font("Baskerville Old Face", 1, 11)); // NOI18N
        jLabel4.setText("4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, 40, -1));

        txtEJE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEJEActionPerformed(evt);
            }
        });
        txtEJE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEJEKeyPressed(evt);
            }
        });
        getContentPane().add(txtEJE, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 59, -1));

        jSeparator14.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator14.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator14.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 20, 110));

        jLabel5.setFont(new java.awt.Font("Baskerville Old Face", 0, 11)); // NOI18N
        jLabel5.setText("Ángulo Articular");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 90, -1));

        jLabel6.setFont(new java.awt.Font("Baskerville Old Face", 1, 11)); // NOI18N
        jLabel6.setText("150°");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 40, -1));

        txtanguloA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtanguloA1ActionPerformed(evt);
            }
        });
        txtanguloA1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtanguloA1KeyPressed(evt);
            }
        });
        getContentPane().add(txtanguloA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 59, -1));

        jSeparator15.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator15.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator15.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 30, 110));

        jLabel7.setFont(new java.awt.Font("Baskerville Old Face", 0, 11)); // NOI18N
        jLabel7.setText("Ángulo Goniaco Inferior");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 130, -1));

        jLabel9.setFont(new java.awt.Font("Baskerville Old Face", 1, 11)); // NOI18N
        jLabel9.setText("75°");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 30, -1));

        txtanguloG1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtanguloG1ActionPerformed(evt);
            }
        });
        txtanguloG1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtanguloG1KeyPressed(evt);
            }
        });
        getContentPane().add(txtanguloG1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 59, -1));

        jSeparator16.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator16.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator16.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 30, 110));

        jLabel18.setFont(new java.awt.Font("Baskerville Old Face", 0, 11)); // NOI18N
        jLabel18.setText("IMPA");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 40, -1));

        jLabel19.setFont(new java.awt.Font("Baskerville Old Face", 1, 11)); // NOI18N
        jLabel19.setText("85-93-97°");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 60, -1));

        txtIMPA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIMPA1ActionPerformed(evt);
            }
        });
        txtIMPA1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIMPA1KeyPressed(evt);
            }
        });
        getContentPane().add(txtIMPA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 59, -1));

        jLabel20.setFont(new java.awt.Font("Baskerville Old Face", 0, 11)); // NOI18N
        jLabel20.setText("Porcentaje JARABAK");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 130, -1));

        jLabel21.setFont(new java.awt.Font("Baskerville Old Face", 0, 11)); // NOI18N
        jLabel21.setText("EJE FACIAL");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 70, -1));

        jLabel22.setFont(new java.awt.Font("Baskerville Old Face", 1, 11)); // NOI18N
        jLabel22.setText("56%");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 40, -1));

        jLabel23.setFont(new java.awt.Font("Baskerville Old Face", 1, 11)); // NOI18N
        jLabel23.setText("90");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 30, -1));

        txtJa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJa1ActionPerformed(evt);
            }
        });
        txtJa1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtJa1KeyPressed(evt);
            }
        });
        getContentPane().add(txtJa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 59, -1));

        txtIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtISActionPerformed(evt);
            }
        });
        txtIS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtISKeyPressed(evt);
            }
        });
        getContentPane().add(txtIS, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, 59, -1));

        jLabel24.setFont(new java.awt.Font("Baskerville Old Face", 0, 11)); // NOI18N
        jLabel24.setText("II-LS");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 210, 40, -1));

        jSeparator17.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator17.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator17.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 10, 110));

        jLabel25.setFont(new java.awt.Font("Baskerville Old Face", 1, 11)); // NOI18N
        jLabel25.setText("0");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 240, 20, -1));

        txtII.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIIActionPerformed(evt);
            }
        });
        txtII.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIIKeyPressed(evt);
            }
        });
        getContentPane().add(txtII, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 280, 59, -1));

        jSeparator18.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator18.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator18.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 10, 110));

        jLabel26.setFont(new java.awt.Font("Baskerville Old Face", 0, 11)); // NOI18N
        jLabel26.setText("FHIS");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 210, 40, -1));

        jLabel27.setFont(new java.awt.Font("Baskerville Old Face", 1, 11)); // NOI18N
        jLabel27.setText("110°-115°");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 240, 60, -1));

        txtFHIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFHISActionPerformed(evt);
            }
        });
        txtFHIS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFHISKeyPressed(evt);
            }
        });
        getContentPane().add(txtFHIS, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 280, 59, -1));

        jSeparator19.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator19.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator19.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 200, 10, 110));

        jSeparator20.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator20.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator20.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 90, 110));

        jLabel28.setFont(new java.awt.Font("Baskerville Old Face", 0, 11)); // NOI18N
        jLabel28.setText("ANB");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 210, 40, -1));

        jLabel29.setFont(new java.awt.Font("Baskerville Old Face", 1, 11)); // NOI18N
        jLabel29.setText("2°");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 240, 30, -1));

        txtANB82.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtANB82ActionPerformed(evt);
            }
        });
        txtANB82.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtANB82KeyPressed(evt);
            }
        });
        getContentPane().add(txtANB82, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 280, 20, -1));

        jSeparator21.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator21.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator21.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 200, 10, 110));

        jSeparator22.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator22.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator22.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator22, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 200, 10, 110));

        jLabel30.setFont(new java.awt.Font("Baskerville Old Face", 1, 11)); // NOI18N
        jLabel30.setText("82°");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 240, 30, -1));

        jLabel31.setFont(new java.awt.Font("Baskerville Old Face", 1, 11)); // NOI18N
        jLabel31.setText("80°");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 240, 30, -1));

        jLabel32.setFont(new java.awt.Font("Baskerville Old Face", 0, 11)); // NOI18N
        jLabel32.setText("PALS");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 210, 40, -1));

        jLabel33.setFont(new java.awt.Font("Baskerville Old Face", 1, 11)); // NOI18N
        jLabel33.setText("4 mm");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 240, 40, -1));

        jSeparator24.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator24.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator24.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator24, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 230, 10, 80));

        jSeparator25.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator25.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator25.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator25, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 230, 10, 80));

        txtPALS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPALSActionPerformed(evt);
            }
        });
        txtPALS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPALSKeyPressed(evt);
            }
        });
        getContentPane().add(txtPALS, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 280, 59, -1));

        txtANB80.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtANB80ActionPerformed(evt);
            }
        });
        txtANB80.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtANB80KeyPressed(evt);
            }
        });
        getContentPane().add(txtANB80, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 280, 20, -1));

        txtANB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtANB2ActionPerformed(evt);
            }
        });
        txtANB2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtANB2KeyPressed(evt);
            }
        });
        getContentPane().add(txtANB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 280, 20, -1));

        jLabel78.setFont(new java.awt.Font("Baskerville Old Face", 0, 11)); // NOI18N
        jLabel78.setText("PALI");
        getContentPane().add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 210, 50, -1));

        jLabel79.setFont(new java.awt.Font("Baskerville Old Face", 1, 11)); // NOI18N
        jLabel79.setText("2 mm");
        getContentPane().add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 240, 40, 20));

        txtPALI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPALIActionPerformed(evt);
            }
        });
        txtPALI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPALIKeyPressed(evt);
            }
        });
        getContentPane().add(txtPALI, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 280, 59, -1));

        jSeparator23.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator23.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator23.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator23, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 200, 10, 110));

        jLabel80.setFont(new java.awt.Font("Baskerville Old Face", 0, 11)); // NOI18N
        jLabel80.setText("PTB");
        getContentPane().add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 210, 40, -1));

        jLabel81.setFont(new java.awt.Font("Baskerville Old Face", 1, 11)); // NOI18N
        jLabel81.setText("-3 mm");
        getContentPane().add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 240, 40, -1));

        txtPTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPTBActionPerformed(evt);
            }
        });
        txtPTB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPTBKeyPressed(evt);
            }
        });
        getContentPane().add(txtPTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 280, 59, -1));

        jSeparator26.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator26.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator26.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator26, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 200, 10, 110));

        jSeparator27.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator27.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator27.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator27, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 200, 10, 110));

        jSeparator28.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator28.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator28, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 1140, 10));

        lbnombre.setFont(new java.awt.Font("Baskerville Old Face", 1, 11)); // NOI18N
        getContentPane().add(lbnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 70, 130, 18));

        lbapellido.setFont(new java.awt.Font("Baskerville Old Face", 1, 11)); // NOI18N
        getContentPane().add(lbapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 70, 130, 18));

        lblnombre10.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        lblnombre10.setText("Curva de Spee: ");
        getContentPane().add(lblnombre10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 120, -1));

        chcurvaleve1.setText("Leve");
        getContentPane().add(chcurvaleve1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, 60, -1));

        chcurvamoderada1.setText("Moderada");
        getContentPane().add(chcurvamoderada1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, 80, -1));

        chcurvasevera.setText("Severa");
        getContentPane().add(chcurvasevera, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 330, 70, -1));

        lblnombre6.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        lblnombre6.setText("DSD:");
        getContentPane().add(lblnombre6, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 330, 40, -1));

        txtDSD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDSDKeyPressed(evt);
            }
        });
        getContentPane().add(txtDSD, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 330, 60, -1));

        lblnombre9.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        lblnombre9.setText("mm.");
        getContentPane().add(lblnombre9, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 330, 30, -1));

        lblnombre8.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        lblnombre8.setText("Clasificación Maxilares:");
        getContentPane().add(lblnombre8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        txtmaxilares.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtmaxilaresKeyPressed(evt);
            }
        });
        getContentPane().add(txtmaxilares, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 380, -1));

        lblnombre7.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        lblnombre7.setText("Entorno Dental:");
        getContentPane().add(lblnombre7, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 360, -1, -1));

        txtEntornoD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEntornoDKeyPressed(evt);
            }
        });
        getContentPane().add(txtEntornoD, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 360, 380, -1));

        lblnombre11.setFont(new java.awt.Font("Baskerville Old Face", 1, 11)); // NOI18N
        lblnombre11.setText("Bandas en:");
        getContentPane().add(lblnombre11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, 70, 20));

        txtbandas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbandasKeyPressed(evt);
            }
        });
        getContentPane().add(txtbandas, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 380, -1));

        lblnombre12.setFont(new java.awt.Font("Baskerville Old Face", 1, 11)); // NOI18N
        lblnombre12.setText("tubos:");
        getContentPane().add(lblnombre12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, 50, 10));

        txttubos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttubosKeyPressed(evt);
            }
        });
        getContentPane().add(txttubos, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 490, 380, -1));

        lblnombre13.setFont(new java.awt.Font("Baskerville Old Face", 1, 11)); // NOI18N
        lblnombre13.setText("Otros:");
        getContentPane().add(lblnombre13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 520, 50, 20));

        txtotros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtotrosActionPerformed(evt);
            }
        });
        txtotros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtotrosKeyPressed(evt);
            }
        });
        getContentPane().add(txtotros, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 520, 380, -1));

        lblnombre14.setFont(new java.awt.Font("Baskerville Old Face", 1, 11)); // NOI18N
        lblnombre14.setText("Aparato tipo:");
        getContentPane().add(lblnombre14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 550, 80, 20));

        txtAparato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAparatoKeyPressed(evt);
            }
        });
        getContentPane().add(txtAparato, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 550, 380, -1));

        lblnombre15.setFont(new java.awt.Font("Baskerville Old Face", 1, 11)); // NOI18N
        lblnombre15.setText("Exodoncia:");
        getContentPane().add(lblnombre15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 580, 70, 20));

        txtexodoncia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtexodonciaKeyPressed(evt);
            }
        });
        getContentPane().add(txtexodoncia, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 580, 380, -1));

        lblnombre17.setFont(new java.awt.Font("Baskerville Old Face", 1, 11)); // NOI18N
        lblnombre17.setText("Brackets:");
        getContentPane().add(lblnombre17, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 610, 60, 20));

        txtBrakets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBraketsActionPerformed(evt);
            }
        });
        txtBrakets.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBraketsKeyPressed(evt);
            }
        });
        getContentPane().add(txtBrakets, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 610, 380, -1));

        lblnombre19.setFont(new java.awt.Font("Baskerville Old Face", 1, 11)); // NOI18N
        lblnombre19.setText("RETENCIONES MX:");
        getContentPane().add(lblnombre19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 640, 110, 20));

        txtRetenciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRetencionesActionPerformed(evt);
            }
        });
        txtRetenciones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRetencionesKeyPressed(evt);
            }
        });
        getContentPane().add(txtRetenciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 640, 380, -1));

        lblnombre18.setFont(new java.awt.Font("Baskerville Old Face", 1, 11)); // NOI18N
        lblnombre18.setText("Secuencia de Arcos:");
        getContentPane().add(lblnombre18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 670, -1, 20));

        txtsecuencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsecuenciaKeyPressed(evt);
            }
        });
        getContentPane().add(txtsecuencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 670, 380, -1));

        lblnombre20.setFont(new java.awt.Font("Baskerville Old Face", 1, 11)); // NOI18N
        lblnombre20.setText("MD:");
        getContentPane().add(lblnombre20, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 700, 40, 20));

        txtMD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMDKeyPressed(evt);
            }
        });
        getContentPane().add(txtMD, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 700, 380, -1));

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jLabel1.setText("Indicación especial antes de colocar Brackets");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 470, 300, -1));

        jLabel83.setFont(new java.awt.Font("Baskerville Old Face", 1, 15)); // NOI18N
        jLabel83.setText("Plan de Tratamiento");
        getContentPane().add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 420, -1, 20));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 620, 400, 10));

        jLabel84.setBackground(new java.awt.Color(0, 0, 0));
        jLabel84.setFont(new java.awt.Font("Baskerville Old Face", 0, 10)); // NOI18N
        jLabel84.setText("Tomar imp.");
        getContentPane().add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 530, 60, -1));

        jLabel85.setBackground(new java.awt.Color(0, 0, 0));
        jLabel85.setFont(new java.awt.Font("Baskerville Old Face", 0, 10)); // NOI18N
        jLabel85.setText("Repetir Fotos");
        getContentPane().add(jLabel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 500, 80, -1));

        jLabel86.setBackground(new java.awt.Color(0, 0, 0));
        jLabel86.setFont(new java.awt.Font("Baskerville Old Face", 0, 10)); // NOI18N
        jLabel86.setText("Tomar Rx");
        getContentPane().add(jLabel86, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 560, 50, -1));

        jSeparator29.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator29, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 490, 400, -1));

        jSeparator30.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator30, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 520, 400, 10));

        jLabel87.setFont(new java.awt.Font("Baskerville Old Face", 0, 10)); // NOI18N
        jLabel87.setText("RX Rocabado");
        getContentPane().add(jLabel87, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 590, 80, -1));

        jSeparator31.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator31, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 550, 400, 10));

        jSeparator32.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator32.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator32.setToolTipText("");
        getContentPane().add(jSeparator32, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 490, 10, 130));

        jSeparator33.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator33.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator33, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 490, -1, 90));

        jSeparator67.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator67.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator67, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 490, -1, 90));

        chmodelo.setBackground(new java.awt.Color(255, 255, 255));
        chmodelo.setText("Modelo mx ");
        getContentPane().add(chmodelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 520, 93, -1));

        chfaciales.setBackground(new java.awt.Color(255, 255, 255));
        chfaciales.setText("Faciales");
        getContentPane().add(chfaciales, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 490, -1, -1));

        chpanoramica.setBackground(new java.awt.Color(255, 255, 255));
        chpanoramica.setText("Panorámica");
        getContentPane().add(chpanoramica, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 550, 93, -1));

        chintraorales.setBackground(new java.awt.Color(255, 255, 255));
        chintraorales.setText("Intraorales");
        getContentPane().add(chintraorales, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 490, 93, -1));

        jSeparator68.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator68.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator68, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 490, -1, 90));

        chmodeloMD.setBackground(new java.awt.Color(255, 255, 255));
        chmodeloMD.setText("Modelo md");
        getContentPane().add(chmodeloMD, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 520, 93, -1));

        chcefalometrica.setBackground(new java.awt.Color(255, 255, 255));
        chcefalometrica.setText("Cefalométrica");
        getContentPane().add(chcefalometrica, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 550, 93, -1));

        chincicivos.setBackground(new java.awt.Color(255, 255, 255));
        chincicivos.setText("Incicivos");
        getContentPane().add(chincicivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 550, 70, -1));

        jSeparator69.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator69.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator69, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 490, -1, 130));

        jSeparator70.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator70, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 580, 400, -1));

        txtrocabado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrocabadoActionPerformed(evt);
            }
        });
        txtrocabado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtrocabadoKeyPressed(evt);
            }
        });
        getContentPane().add(txtrocabado, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 590, 280, -1));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator7.setToolTipText("");
        getContentPane().add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 450, 12, 320));

        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator8.setToolTipText("");
        getContentPane().add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 1350, 10));

        btnBuscarEditar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/buscar edicion.png"))); // NOI18N
        btnBuscarEditar1.setText("Buscar para Editar");
        btnBuscarEditar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuscarEditar1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btnBuscarEditar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 200, 120, -1));

        btnEditar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/editar.png"))); // NOI18N
        btnEditar1.setText("Editar");
        btnEditar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditar1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btnEditar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 200, 120, -1));

        btnGuardar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/guardar.png"))); // NOI18N
        btnGuardar1.setText("Guardar");
        btnGuardar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardar1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 310, 120, -1));

        btnCancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cancelar.png"))); // NOI18N
        btnCancelar1.setText("Cancelar");
        btnCancelar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btnCancelar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 310, 120, 90));

        btnBuscarEditar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/buscar edicion.png"))); // NOI18N
        btnBuscarEditar2.setText("Buscar para Editar");
        btnBuscarEditar2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuscarEditar2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btnBuscarEditar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 670, -1, -1));

        btnEditar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/editar.png"))); // NOI18N
        btnEditar2.setText("Editar");
        btnEditar2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditar2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btnEditar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 670, -1, -1));

        btnGuardarPT2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/guardar.png"))); // NOI18N
        btnGuardarPT2.setText("Guardar");
        btnGuardarPT2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardarPT2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGuardarPT2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarPT2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardarPT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 670, -1, -1));

        btnCancelar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cancelar.png"))); // NOI18N
        btnCancelar2.setText("Cancelar");
        btnCancelar2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btnCancelar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 670, -1, 90));

        btnElegirTP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/elegir tp.png"))); // NOI18N
        btnElegirTP.setText("Elegir tipo de paciente");
        btnElegirTP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnElegirTP.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btnElegirTP, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 180, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEJEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEJEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEJEActionPerformed

    private void txtEJEKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEJEKeyPressed

    }//GEN-LAST:event_txtEJEKeyPressed

    private void txtanguloA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtanguloA1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtanguloA1ActionPerformed

    private void txtanguloA1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtanguloA1KeyPressed

    }//GEN-LAST:event_txtanguloA1KeyPressed

    private void txtanguloG1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtanguloG1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtanguloG1ActionPerformed

    private void txtanguloG1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtanguloG1KeyPressed

    }//GEN-LAST:event_txtanguloG1KeyPressed

    private void txtIMPA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIMPA1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIMPA1ActionPerformed

    private void txtIMPA1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIMPA1KeyPressed

    }//GEN-LAST:event_txtIMPA1KeyPressed

    private void txtJa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJa1ActionPerformed

    private void txtJa1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJa1KeyPressed

    }//GEN-LAST:event_txtJa1KeyPressed

    private void txtISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtISActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtISActionPerformed

    private void txtISKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtISKeyPressed

    }//GEN-LAST:event_txtISKeyPressed

    private void txtIIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIIActionPerformed

    private void txtIIKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIIKeyPressed

    }//GEN-LAST:event_txtIIKeyPressed

    private void txtFHISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFHISActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFHISActionPerformed

    private void txtFHISKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFHISKeyPressed

    }//GEN-LAST:event_txtFHISKeyPressed

    private void txtANB82ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtANB82ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtANB82ActionPerformed

    private void txtANB82KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtANB82KeyPressed

    }//GEN-LAST:event_txtANB82KeyPressed

    private void txtPALSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPALSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPALSActionPerformed

    private void txtPALSKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPALSKeyPressed

    }//GEN-LAST:event_txtPALSKeyPressed

    private void txtANB80ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtANB80ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtANB80ActionPerformed

    private void txtANB80KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtANB80KeyPressed

    }//GEN-LAST:event_txtANB80KeyPressed

    private void txtANB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtANB2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtANB2ActionPerformed

    private void txtANB2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtANB2KeyPressed

    }//GEN-LAST:event_txtANB2KeyPressed

    private void txtPALIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPALIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPALIActionPerformed

    private void txtPALIKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPALIKeyPressed

    }//GEN-LAST:event_txtPALIKeyPressed

    private void txtPTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPTBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPTBActionPerformed

    private void txtPTBKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPTBKeyPressed

    }//GEN-LAST:event_txtPTBKeyPressed

    private void txtDSDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDSDKeyPressed

    }//GEN-LAST:event_txtDSDKeyPressed

    private void txtmaxilaresKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmaxilaresKeyPressed

    }//GEN-LAST:event_txtmaxilaresKeyPressed

    private void txtEntornoDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEntornoDKeyPressed

    }//GEN-LAST:event_txtEntornoDKeyPressed

    private void txtbandasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbandasKeyPressed

    }//GEN-LAST:event_txtbandasKeyPressed

    private void txttubosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttubosKeyPressed

    }//GEN-LAST:event_txttubosKeyPressed

    private void txtotrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtotrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtotrosActionPerformed

    private void txtotrosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtotrosKeyPressed

    }//GEN-LAST:event_txtotrosKeyPressed

    private void txtAparatoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAparatoKeyPressed

    }//GEN-LAST:event_txtAparatoKeyPressed

    private void txtexodonciaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtexodonciaKeyPressed

    }//GEN-LAST:event_txtexodonciaKeyPressed

    private void txtBraketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBraketsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBraketsActionPerformed

    private void txtBraketsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBraketsKeyPressed

    }//GEN-LAST:event_txtBraketsKeyPressed

    private void txtRetencionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRetencionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRetencionesActionPerformed

    private void txtRetencionesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRetencionesKeyPressed

    }//GEN-LAST:event_txtRetencionesKeyPressed

    private void txtsecuenciaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsecuenciaKeyPressed

    }//GEN-LAST:event_txtsecuenciaKeyPressed

    private void txtMDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMDKeyPressed

    }//GEN-LAST:event_txtMDKeyPressed

    private void txtrocabadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrocabadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrocabadoActionPerformed

    private void txtrocabadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrocabadoKeyPressed

    }//GEN-LAST:event_txtrocabadoKeyPressed

    private void btnGuardarPT2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarPT2ActionPerformed
//       ConexionDB trata = new ConexionDB();
//       trata.procedureIngresarTrataOr(txtbandas.getText(), txttubos.getText(), txtotros.getText(), txtAparato.getText(), 
//               txtexodoncia.getText(), txtBrakets.getText(), txtRetenciones.getText(), txtMD.getText(),1);
//       
//        JOptionPane.showMessageDialog(null, "Paciente Almacenado");

 int seleccion3 = 0;
        if(this.chfaciales.isSelected()== true ) {
             seleccion3 = 1;
            }else{
            seleccion3 = 0;
        }
        int f_faciales= seleccion3;
        // validaciones chintraorales
        int seleccion4 = 0;
        if(this.chintraorales.isSelected()== true ) {
             seleccion4 = 1;
            }else{
            seleccion4 = 0;
        }
        int f_intraorales = seleccion4;
        //validacion chmodelo
        int seleccion5 = 0;
        if(this.chmodelo.isSelected()== true ) {
             seleccion5 = 1;
            }else{
            seleccion5 = 0;
        }
        int modelo_mx = seleccion5;
        //validacion chmodeloMD
        int seleccion6 = 0;
        if(this.chmodeloMD.isSelected()== true ) {
             seleccion6 = 1;
            }else{
            seleccion6 = 0;
        }
        int modelo_md = seleccion6;
        //validacion chpanoramica
        int seleccion7 = 0;
        if(this.chpanoramica.isSelected()== true ) {
             seleccion7 = 1;
            }else{
            seleccion7 = 0;
        }
        int rx_panoramica = seleccion7;
        //validacion chcefalometrica
        int seleccion8 = 0;
        if(this.chcefalometrica.isSelected()== true ) {
             seleccion8 = 1;
            }else{
            seleccion8 = 0;
        }
        int rx_cefalometria = seleccion8;
        //validacion chincicivos
         int seleccion9 = 0;
        if(this.chincicivos.isSelected()== true ) {
             seleccion9 = 1;
            }else{
            seleccion9 = 0;
        }
        int rx_incicivos = seleccion9;
        String rx_rocabado = this.txtrocabado.getText();
        
        ConexionDB indicaciones = new ConexionDB();
        
        indicaciones.procedureIndicacionEspecial(f_faciales, f_intraorales, modelo_mx, modelo_md, rx_panoramica, 
                rx_cefalometria, rx_incicivos, rx_rocabado, 1);
        
        
    }//GEN-LAST:event_btnGuardarPT2ActionPerformed

    private void btnGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar1ActionPerformed
//       ConexionDB cefalometria = new ConexionDB();
//       cefalometria.procedureIngresarCefalom(txtanguloA1.getText(), txtanguloG1.getText(), txtIMPA1.getText(), txtJa1.getText(), 
//               txtEJE.getText(), txtIS.getText(), txtII.getText(), txtFHIS.getText(), txtANB82.getText(), txtANB80.getText(),
//               txtANB2.getText(), txtPALS.getText(), txtPALI.getText(), txtPTB.getText(), txtDSD.getText(), 
//               txtmaxilares.getText(), txtEntornoD.getText(),2);
//       JOptionPane.showMessageDialog(null, "Tratamiento Almacenado");
       
       int seleccion = 0;
        if(this.chcurvaleve1.isSelected()== true ) {
             seleccion = 1;
            }else{
            seleccion = 0;
        }
        int speeleve= seleccion;
         int seleccion1 = 0;
        if(this.chcurvamoderada1.isSelected()== true ) {
             seleccion1 = 1;
            }else{
            seleccion1 = 0;
        }
        int speemoderada= seleccion1;
          int seleccion2 = 0;
        if(this.chcurvasevera.isSelected()== true ) {
             seleccion2 = 1;
            }else{
            seleccion2 = 0;
        }
        int speesvera= seleccion2;
       
       ConexionDB spee = new ConexionDB();
       
       spee.procedureTrataSpee(speeleve, speemoderada, speesvera,1);
      
       
       
    }//GEN-LAST:event_btnGuardar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarEditar1;
    private javax.swing.JButton btnBuscarEditar2;
    private javax.swing.JButton btnCancelar1;
    private javax.swing.JButton btnCancelar2;
    private javax.swing.JButton btnEditar1;
    private javax.swing.JButton btnEditar2;
    private javax.swing.JButton btnElegirTP;
    private javax.swing.JButton btnGuardar1;
    private javax.swing.JButton btnGuardarPT2;
    private javax.swing.JCheckBox chcefalometrica;
    private javax.swing.JCheckBox chcurvaleve1;
    private javax.swing.JCheckBox chcurvamoderada1;
    private javax.swing.JCheckBox chcurvasevera;
    private javax.swing.JCheckBox chfaciales;
    private javax.swing.JCheckBox chincicivos;
    private javax.swing.JCheckBox chintraorales;
    private javax.swing.JCheckBox chmodelo;
    private javax.swing.JCheckBox chmodeloMD;
    private javax.swing.JCheckBox chpanoramica;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator27;
    private javax.swing.JSeparator jSeparator28;
    private javax.swing.JSeparator jSeparator29;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator30;
    private javax.swing.JSeparator jSeparator31;
    private javax.swing.JSeparator jSeparator32;
    private javax.swing.JSeparator jSeparator33;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator67;
    private javax.swing.JSeparator jSeparator68;
    private javax.swing.JSeparator jSeparator69;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator70;
    private javax.swing.JSeparator jSeparator8;
    public static javax.swing.JLabel lbapellido;
    public static javax.swing.JLabel lbid;
    public static javax.swing.JLabel lbidplan;
    private javax.swing.JLabel lblnombre10;
    private javax.swing.JLabel lblnombre11;
    private javax.swing.JLabel lblnombre12;
    private javax.swing.JLabel lblnombre13;
    private javax.swing.JLabel lblnombre14;
    private javax.swing.JLabel lblnombre15;
    private javax.swing.JLabel lblnombre17;
    private javax.swing.JLabel lblnombre18;
    private javax.swing.JLabel lblnombre19;
    private javax.swing.JLabel lblnombre20;
    private javax.swing.JLabel lblnombre6;
    private javax.swing.JLabel lblnombre7;
    private javax.swing.JLabel lblnombre8;
    private javax.swing.JLabel lblnombre9;
    public static javax.swing.JLabel lbnombre;
    public static javax.swing.JTextField txtANB2;
    public static javax.swing.JTextField txtANB80;
    public static javax.swing.JTextField txtANB82;
    public static javax.swing.JTextField txtAparato;
    public static javax.swing.JTextField txtBrakets;
    public static javax.swing.JTextField txtDSD;
    public static javax.swing.JTextField txtEJE;
    public static javax.swing.JTextField txtEntornoD;
    public static javax.swing.JTextField txtFHIS;
    public static javax.swing.JTextField txtII;
    public static javax.swing.JTextField txtIMPA1;
    public static javax.swing.JTextField txtIS;
    public static javax.swing.JTextField txtJa1;
    public static javax.swing.JTextField txtMD;
    public static javax.swing.JTextField txtPALI;
    public static javax.swing.JTextField txtPALS;
    public static javax.swing.JTextField txtPTB;
    public static javax.swing.JTextField txtRetenciones;
    public static javax.swing.JTextField txtanguloA1;
    public static javax.swing.JTextField txtanguloG1;
    public static javax.swing.JTextField txtbandas;
    public static javax.swing.JTextField txtexodoncia;
    public static javax.swing.JTextField txtmaxilares;
    public static javax.swing.JTextField txtotros;
    public static javax.swing.JTextField txtrocabado;
    public static javax.swing.JTextField txtsecuencia;
    public static javax.swing.JTextField txttubos;
    // End of variables declaration//GEN-END:variables
}
